/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practicaad1._limpiezadediscos.Vista;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import practicaad1._limpiezadediscos.Logica.GestionLimpiezaDiscos;
import practicaad1._limpiezadediscos.Logica.MisExcepciones;

/**
 *
 * @author migue
 */
public class jFrameLimpiezaDiscos extends javax.swing.JFrame {

    JFileChooser chooser = new JFileChooser();
    GestionLimpiezaDiscos gestion;

    /**
     * Creates new form jFrameLimpiezaDiscos
     */
    public jFrameLimpiezaDiscos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jCheckBoxEliminarDirectoriosVacios = new javax.swing.JCheckBox();
        jCheckBoxEliminarFicherosPorCategoria = new javax.swing.JCheckBox();
        jCheckBoxEliminarFicherosGranTamaño = new javax.swing.JCheckBox();
        jCheckBoxEliminarFicherosAntiguos = new javax.swing.JCheckBox();
        jCheckBoxBuscarFicherosDuplicados = new javax.swing.JCheckBox();
        jButtonSeleccionarUnidad = new javax.swing.JButton();
        jLabelUnidad = new javax.swing.JLabel();
        jBContinuar = new javax.swing.JButton();
        jComboBoxCategoriasFichero = new javax.swing.JComboBox<>();
        jSpinnerTamano = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelTitulo.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabelTitulo.setText("Herramienta de limpieza de discos");

        jCheckBoxEliminarDirectoriosVacios.setText("Eliminar directorios Vacios");

        jCheckBoxEliminarFicherosPorCategoria.setText("Eliminar ficheros por categoria");

        jCheckBoxEliminarFicherosGranTamaño.setText("Eliminar ficheros de gran tamaño");

        jCheckBoxEliminarFicherosAntiguos.setText("Eliminar ficheros antiguos");

        jCheckBoxBuscarFicherosDuplicados.setText("Buscar ficheros duplicados");

        jButtonSeleccionarUnidad.setText("Seleccionar unidad");
        jButtonSeleccionarUnidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeleccionarUnidadActionPerformed(evt);
            }
        });

        jBContinuar.setText("Continuar");
        jBContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBContinuarActionPerformed(evt);
            }
        });

        jComboBoxCategoriasFichero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Imagenes", "Videos", "Audios", "Documentos" }));

        jSpinnerTamano.setModel(new javax.swing.SpinnerNumberModel(0, null, null, 5));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonSeleccionarUnidad)
                        .addGap(23, 23, 23)
                        .addComponent(jLabelUnidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBContinuar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxEliminarFicherosAntiguos)
                            .addComponent(jCheckBoxBuscarFicherosDuplicados)
                            .addComponent(jCheckBoxEliminarDirectoriosVacios)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBoxEliminarFicherosGranTamaño)
                                    .addComponent(jCheckBoxEliminarFicherosPorCategoria))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBoxCategoriasFichero, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSpinnerTamano, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSeleccionarUnidad)
                    .addComponent(jLabelUnidad))
                .addGap(20, 20, 20)
                .addComponent(jCheckBoxEliminarDirectoriosVacios)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxEliminarFicherosPorCategoria)
                    .addComponent(jComboBoxCategoriasFichero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxEliminarFicherosGranTamaño)
                    .addComponent(jSpinnerTamano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jCheckBoxEliminarFicherosAntiguos)
                .addGap(18, 18, 18)
                .addComponent(jCheckBoxBuscarFicherosDuplicados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jBContinuar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSeleccionarUnidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeleccionarUnidadActionPerformed
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        chooser.showOpenDialog(jFrameLimpiezaDiscos.this);
        jLabelUnidad.setText(chooser.getSelectedFile().getPath());
        gestion = new GestionLimpiezaDiscos(chooser.getSelectedFile());
    }//GEN-LAST:event_jButtonSeleccionarUnidadActionPerformed

    private void jBContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBContinuarActionPerformed
        int seleccionados = 0;
        if (jCheckBoxEliminarDirectoriosVacios.isSelected()) {
            seleccionados++;
            int directoriosVaciosBorrados = gestion.eliminarDirectoriosVacios();
            JOptionPane.showMessageDialog(this, "Se han borrado " + directoriosVaciosBorrados + " directorios vacios de la carpeta " + gestion.getUnidad().getPath());
        } else if (jCheckBoxEliminarFicherosPorCategoria.isSelected()) {
            seleccionados++;
            int opcion = JOptionPane.showConfirmDialog(this, "¿Esta seguro que desea borrar todos los archivos de la categoria : " + jComboBoxCategoriasFichero.getSelectedItem().toString() + " de la carpeta " + gestion.getUnidad().getPath() + " ?", "dialogo confirmacion", JOptionPane.YES_NO_OPTION);
            if (opcion == JOptionPane.YES_OPTION) {
                try {
                    int ficherosEliminados = gestion.eliminarFicherosPorCategoria(jComboBoxCategoriasFichero.getSelectedItem().toString());
                    JOptionPane.showMessageDialog(this, "Se han borrado " + ficherosEliminados + " ficheros de la carpeta " + gestion.getUnidad().getPath());
                } catch (MisExcepciones.NoExisteDirectorio ex) {
                    Logger.getLogger(jFrameLimpiezaDiscos.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } else if (jCheckBoxEliminarFicherosGranTamaño.isSelected()) {
            seleccionados++;
            int ficherosBorradosPorTamano = 0;
            try {
                gestion.eliminarFicherosPorTamaño((int) jSpinnerTamano.getValue());
                JOptionPane.showMessageDialog(this, "Se han borrado " + ficherosBorradosPorTamano + " ficheros de la carpeta " + gestion.getUnidad().getPath());
            } catch (MisExcepciones.NoExisteDirectorio ex) {
                Logger.getLogger(jFrameLimpiezaDiscos.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else if (jCheckBoxEliminarFicherosAntiguos.isSelected()) {
            seleccionados++;

        } else if (jCheckBoxBuscarFicherosDuplicados.isSelected()) {
            seleccionados++;

        }
    }//GEN-LAST:event_jBContinuarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jFrameLimpiezaDiscos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jFrameLimpiezaDiscos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jFrameLimpiezaDiscos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jFrameLimpiezaDiscos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jFrameLimpiezaDiscos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBContinuar;
    private javax.swing.JButton jButtonSeleccionarUnidad;
    private javax.swing.JCheckBox jCheckBoxBuscarFicherosDuplicados;
    private javax.swing.JCheckBox jCheckBoxEliminarDirectoriosVacios;
    private javax.swing.JCheckBox jCheckBoxEliminarFicherosAntiguos;
    private javax.swing.JCheckBox jCheckBoxEliminarFicherosGranTamaño;
    private javax.swing.JCheckBox jCheckBoxEliminarFicherosPorCategoria;
    private javax.swing.JComboBox<String> jComboBoxCategoriasFichero;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelUnidad;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jSpinnerTamano;
    // End of variables declaration//GEN-END:variables
}
